name: Plugin Name
author: RKN777
category: Interface
tags: [animation, canvas]
docs: http://devthought.com/projects/mootools/textboxlist/
demo: http://devthought.com/wp-content/project/mootools/textboxlist/Demo/
